Is_Cursor_Active:
   default: false
   description: "Enable the pointer to change states."
   type: bool

Background_Image:
  type: upload
  default: ""
  description: "Upload a background image. Note: If you do not apply this, the background will be grey, and blur will not apply on the sidebar or body."
   
Is_Background_Blurred:
   default: true
   description: "Enables body background blur. WARNING: Enforces a dark background as of right now"
   type: bool
   
Background_Type:
  default: scale_to_fit
  type: enum
  choices:
    - tile
    - scale_to_fit
  description: "Choose to have your custom background scaled to fit, or tiled"
  
Tile_Size:
   default: "150px"
   description: "Size for the tile background type. Will only work if Background Type is set to tile. WARNING: You must include 'px' at the end of it, or it wont work!"
   type: string
   
Post_Tags:
   default: true
   description: "Enables Staff tag next to admins and moderators, and \"OP\" next to the topic owner."
   type: bool
